name: RsMetaCheck

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your code
        uses: actions/checkout@v4

      - name: Run RsMetaCheck

        uses: SoftwareUnderstanding/rs-metacheck-action@main
        with:
          input: "https://github.com/${{ github.repository }}"
          pitfalls_output: "./pitfalls_results"
          verbose: "true"

      - name: Save Results
        uses: actions/upload-artifact@v4
        with:
          name: metadata-report
          path: ./pitfalls_results/
